name = "GenshinHelp"
uuid = "d7ccf301-f71d-49d9-ab47-99bb49bd8dbe"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[deps]
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
LazyJSON = "fc18253b-5e1b-504c-a4a2-9ece4944c004"

[compat]
LazyJSON = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Jive"]
