name: CI

on:
  push:
    paths-ignore:
      - README.md
  pull_request:

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.6.2]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: test js
        run: |
             cd test/genshin-db
             make deps
             make
      - name: runtests
        run: |
             julia --project=. -e 'using Pkg; Pkg.test()'
